export type AppErrorCode =
  | "INVALID_CREDENTIALS"
  | "SESSION_EXPIRED"
  | "SESSION_NOT_FOUND"
  | "EMAIL_NOT_VERIFIED"
  | "OAUTH_CLIENT_INVALID"
  | "OAUTH_REDIRECT_URI_INVALID"
  | "OAUTH_SCOPE_INVALID"
  | "NETWORK_ERROR"
  | "RATE_LIMITED"
  | "OPERATION_UNSUPPORTED"
  | "INVALID_API_RESPONSE"
  | "UNKNOWN_ERROR";
