export const AUDIT_EVENT_TYPES = Object.freeze({
  LOGIN_SUCCESS: "login_success",
  HANDOFF_ISSUED: "handoff_issued",
  HANDOFF_CONSUMED: "handoff_consumed",
  CONSENT_GRANTED: "consent_granted",
  CONSENT_DENIED: "consent_denied",
  PROFILE_UPDATED: "profile_updated",
  PASSWORD_CHANGED: "password_changed",
  PASSWORD_RESET: "password_reset",
  EMAIL_VERIFIED: "email_verified",
  APPLICATION_REVOKED: "application_revoked",
  CONSOLE_CLIENT_CREATED: "console_client_created",
  CONSOLE_CLIENT_UPDATED: "console_client_updated",
  CONSOLE_CLIENT_DISABLED: "console_client_disabled",
  CONSOLE_CLIENT_ACTIVATED: "console_client_activated",
  CONSOLE_APPLICATION_REQUEST_APPROVED: "console_application_request_approved",
  CONSOLE_APPLICATION_REQUEST_REJECTED: "console_application_request_rejected",
  REGISTRATION_CONFIG_UPDATED: "registration_config_updated",
  REGISTRATION_REVIEW_COMPENSATION_FAILED: "registration_review_compensation_failed",
  REGISTRATION_APPROVED: "registration_approved",
  REGISTRATION_REJECTED: "registration_rejected",
  REGISTRATION_APPROVE_FAILED: "registration_approve_failed",
  REGISTRATION_REJECT_FAILED: "registration_reject_failed",
  REGISTRATION_REVIEW_RECONCILED: "registration_review_reconciled",
  ADMIN_USER_ACTIVE: "admin_user_active",
  ADMIN_USER_DISABLED: "admin_user_disabled",
  ADMIN_USER_PASSWORD_RESET_REQUESTED: "admin_user_password_reset_requested",
});
